nama = input("Nama\t\t\t: ")
nim = input("NIM\t\t\t: ")
kelas_paralel = input("Kelas Paralel\t\t: ")
ttl = input("Tempat/Tanggal Lahir\t: ")
alamat = input("Alamat\t\t\t: ")
hobby = input("Hobby\t\t\t: ")
no_hp = input("No. HP\t\t\t: ")

print(f"\nNama\t\t\t:{nama}")
print(f"NIM\t\t\t:{nim}")
print(f"Kelas Paralel\t\t:{kelas_paralel}")
print(f"Tempat/Tanggal Lahir\t:{ttl}")
print(f"Alamat\t\t\t:{alamat}")
print(f"Hobby\t\t\t:{hobby}")
print(f"No.HP\t\t\t:{no_hp}") 